### PR TITLE
Proxy on* handlers defined as strings when allow-events is enabled

### PR DESCRIPTION
**Pull request by AkeemMcLennon**
After well over a month (I've been busy / out of the country), this is the second PR resulting from our discussion at developit/preact#95

It depends on https://github.com/developit/preact/pull/142 being merged (and possibly published to npm?) before tests can pass.

### CODE REVIEW

**Comment by developit** [comment]
Looks awesome @AkeemMcLennon. I'm thinking for now we should have the tests expect to see an error thrown when firing the string event handler. Do you want to update, or should I just merge and then update the test?

**Comment by AkeemMcLennon** [comment]
@developit I'll go ahead and make the update in both PRs

**Comment by developit** [comment]
Awesome!

**Comment by AkeemMcLennon** [comment]
I've updated the test, but I'm not sure what to make of the rollup error in Travis CI

**Comment by AkeemMcLennon** [comment]
Updated to a new rollup version that fixes https://github.com/rollup/rollup/issues/618

Builds now pass

**Comment by developit** [comment]
Awesome, thanks for making that work!!

**Pull request merged**
